package com.yadda.integrate.model;

import java.util.Date;

public class AppUser extends RootModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FUserID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Integer fuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FNumber
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String fnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FName
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FGender
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Integer fgender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FPassword
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String fpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FStatus
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Boolean fstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FHeadUrl
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String fheadurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FCreateTime
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Date fcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FBalance
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Float fbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FAutoPay
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Integer fautopay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FCouponCode
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String fcouponcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FCouponCodeStatus
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Integer fcouponcodestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FOpenID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String fopenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FShareAmount
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Float fshareamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FShareBalance
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Float fsharebalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FOccurredAmount
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Float foccurredamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FCardNum
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String fcardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AppUser.FScene
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String fscene;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FUserID
     *
     * @return the value of t_AppUser.FUserID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Integer getFuserid() {
        return fuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FUserID
     *
     * @param fuserid the value for t_AppUser.FUserID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFuserid(Integer fuserid) {
        this.fuserid = fuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FNumber
     *
     * @return the value of t_AppUser.FNumber
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FNumber
     *
     * @param fnumber the value for t_AppUser.FNumber
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFnumber(String fnumber) {
        this.fnumber = fnumber == null ? null : fnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FName
     *
     * @return the value of t_AppUser.FName
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FName
     *
     * @param fname the value for t_AppUser.FName
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FGender
     *
     * @return the value of t_AppUser.FGender
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Integer getFgender() {
        return fgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FGender
     *
     * @param fgender the value for t_AppUser.FGender
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFgender(Integer fgender) {
        this.fgender = fgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FPassword
     *
     * @return the value of t_AppUser.FPassword
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getFpassword() {
        return fpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FPassword
     *
     * @param fpassword the value for t_AppUser.FPassword
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFpassword(String fpassword) {
        this.fpassword = fpassword == null ? null : fpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FStatus
     *
     * @return the value of t_AppUser.FStatus
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Boolean getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FStatus
     *
     * @param fstatus the value for t_AppUser.FStatus
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFstatus(Boolean fstatus) {
        this.fstatus = fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FHeadUrl
     *
     * @return the value of t_AppUser.FHeadUrl
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getFheadurl() {
        return fheadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FHeadUrl
     *
     * @param fheadurl the value for t_AppUser.FHeadUrl
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFheadurl(String fheadurl) {
        this.fheadurl = fheadurl == null ? null : fheadurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FCreateTime
     *
     * @return the value of t_AppUser.FCreateTime
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Date getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FCreateTime
     *
     * @param fcreatetime the value for t_AppUser.FCreateTime
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFcreatetime(Date fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FBalance
     *
     * @return the value of t_AppUser.FBalance
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Float getFbalance() {
        return fbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FBalance
     *
     * @param fbalance the value for t_AppUser.FBalance
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFbalance(Float fbalance) {
        this.fbalance = fbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FAutoPay
     *
     * @return the value of t_AppUser.FAutoPay
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Integer getFautopay() {
        return fautopay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FAutoPay
     *
     * @param fautopay the value for t_AppUser.FAutoPay
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFautopay(Integer fautopay) {
        this.fautopay = fautopay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FCouponCode
     *
     * @return the value of t_AppUser.FCouponCode
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getFcouponcode() {
        return fcouponcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FCouponCode
     *
     * @param fcouponcode the value for t_AppUser.FCouponCode
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFcouponcode(String fcouponcode) {
        this.fcouponcode = fcouponcode == null ? null : fcouponcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FCouponCodeStatus
     *
     * @return the value of t_AppUser.FCouponCodeStatus
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Integer getFcouponcodestatus() {
        return fcouponcodestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FCouponCodeStatus
     *
     * @param fcouponcodestatus the value for t_AppUser.FCouponCodeStatus
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFcouponcodestatus(Integer fcouponcodestatus) {
        this.fcouponcodestatus = fcouponcodestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FOpenID
     *
     * @return the value of t_AppUser.FOpenID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getFopenid() {
        return fopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FOpenID
     *
     * @param fopenid the value for t_AppUser.FOpenID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFopenid(String fopenid) {
        this.fopenid = fopenid == null ? null : fopenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FShareAmount
     *
     * @return the value of t_AppUser.FShareAmount
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Float getFshareamount() {
        return fshareamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FShareAmount
     *
     * @param fshareamount the value for t_AppUser.FShareAmount
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFshareamount(Float fshareamount) {
        this.fshareamount = fshareamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FShareBalance
     *
     * @return the value of t_AppUser.FShareBalance
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Float getFsharebalance() {
        return fsharebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FShareBalance
     *
     * @param fsharebalance the value for t_AppUser.FShareBalance
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFsharebalance(Float fsharebalance) {
        this.fsharebalance = fsharebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FOccurredAmount
     *
     * @return the value of t_AppUser.FOccurredAmount
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Float getFoccurredamount() {
        return foccurredamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FOccurredAmount
     *
     * @param foccurredamount the value for t_AppUser.FOccurredAmount
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFoccurredamount(Float foccurredamount) {
        this.foccurredamount = foccurredamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FCardNum
     *
     * @return the value of t_AppUser.FCardNum
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getFcardnum() {
        return fcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FCardNum
     *
     * @param fcardnum the value for t_AppUser.FCardNum
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFcardnum(String fcardnum) {
        this.fcardnum = fcardnum == null ? null : fcardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AppUser.FScene
     *
     * @return the value of t_AppUser.FScene
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getFscene() {
        return fscene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AppUser.FScene
     *
     * @param fscene the value for t_AppUser.FScene
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setFscene(String fscene) {
        this.fscene = fscene == null ? null : fscene.trim();
    }
}