package com.yadda.integrate.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public AppUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFuseridIsNull() {
            addCriterion("FUserID is null");
            return (Criteria) this;
        }

        public Criteria andFuseridIsNotNull() {
            addCriterion("FUserID is not null");
            return (Criteria) this;
        }

        public Criteria andFuseridEqualTo(Integer value) {
            addCriterion("FUserID =", value, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridNotEqualTo(Integer value) {
            addCriterion("FUserID <>", value, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridGreaterThan(Integer value) {
            addCriterion("FUserID >", value, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("FUserID >=", value, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridLessThan(Integer value) {
            addCriterion("FUserID <", value, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridLessThanOrEqualTo(Integer value) {
            addCriterion("FUserID <=", value, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridIn(List<Integer> values) {
            addCriterion("FUserID in", values, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridNotIn(List<Integer> values) {
            addCriterion("FUserID not in", values, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridBetween(Integer value1, Integer value2) {
            addCriterion("FUserID between", value1, value2, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("FUserID not between", value1, value2, "fuserid");
            return (Criteria) this;
        }

        public Criteria andFnumberIsNull() {
            addCriterion("FNumber is null");
            return (Criteria) this;
        }

        public Criteria andFnumberIsNotNull() {
            addCriterion("FNumber is not null");
            return (Criteria) this;
        }

        public Criteria andFnumberEqualTo(String value) {
            addCriterion("FNumber =", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberNotEqualTo(String value) {
            addCriterion("FNumber <>", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberGreaterThan(String value) {
            addCriterion("FNumber >", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberGreaterThanOrEqualTo(String value) {
            addCriterion("FNumber >=", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberLessThan(String value) {
            addCriterion("FNumber <", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberLessThanOrEqualTo(String value) {
            addCriterion("FNumber <=", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberLike(String value) {
            addCriterion("FNumber like", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberNotLike(String value) {
            addCriterion("FNumber not like", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberIn(List<String> values) {
            addCriterion("FNumber in", values, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberNotIn(List<String> values) {
            addCriterion("FNumber not in", values, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberBetween(String value1, String value2) {
            addCriterion("FNumber between", value1, value2, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberNotBetween(String value1, String value2) {
            addCriterion("FNumber not between", value1, value2, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnameIsNull() {
            addCriterion("FName is null");
            return (Criteria) this;
        }

        public Criteria andFnameIsNotNull() {
            addCriterion("FName is not null");
            return (Criteria) this;
        }

        public Criteria andFnameEqualTo(String value) {
            addCriterion("FName =", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotEqualTo(String value) {
            addCriterion("FName <>", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThan(String value) {
            addCriterion("FName >", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThanOrEqualTo(String value) {
            addCriterion("FName >=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThan(String value) {
            addCriterion("FName <", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThanOrEqualTo(String value) {
            addCriterion("FName <=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLike(String value) {
            addCriterion("FName like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotLike(String value) {
            addCriterion("FName not like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameIn(List<String> values) {
            addCriterion("FName in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotIn(List<String> values) {
            addCriterion("FName not in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameBetween(String value1, String value2) {
            addCriterion("FName between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotBetween(String value1, String value2) {
            addCriterion("FName not between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFgenderIsNull() {
            addCriterion("FGender is null");
            return (Criteria) this;
        }

        public Criteria andFgenderIsNotNull() {
            addCriterion("FGender is not null");
            return (Criteria) this;
        }

        public Criteria andFgenderEqualTo(Integer value) {
            addCriterion("FGender =", value, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderNotEqualTo(Integer value) {
            addCriterion("FGender <>", value, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderGreaterThan(Integer value) {
            addCriterion("FGender >", value, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("FGender >=", value, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderLessThan(Integer value) {
            addCriterion("FGender <", value, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderLessThanOrEqualTo(Integer value) {
            addCriterion("FGender <=", value, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderIn(List<Integer> values) {
            addCriterion("FGender in", values, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderNotIn(List<Integer> values) {
            addCriterion("FGender not in", values, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderBetween(Integer value1, Integer value2) {
            addCriterion("FGender between", value1, value2, "fgender");
            return (Criteria) this;
        }

        public Criteria andFgenderNotBetween(Integer value1, Integer value2) {
            addCriterion("FGender not between", value1, value2, "fgender");
            return (Criteria) this;
        }

        public Criteria andFpasswordIsNull() {
            addCriterion("FPassword is null");
            return (Criteria) this;
        }

        public Criteria andFpasswordIsNotNull() {
            addCriterion("FPassword is not null");
            return (Criteria) this;
        }

        public Criteria andFpasswordEqualTo(String value) {
            addCriterion("FPassword =", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordNotEqualTo(String value) {
            addCriterion("FPassword <>", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordGreaterThan(String value) {
            addCriterion("FPassword >", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("FPassword >=", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordLessThan(String value) {
            addCriterion("FPassword <", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordLessThanOrEqualTo(String value) {
            addCriterion("FPassword <=", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordLike(String value) {
            addCriterion("FPassword like", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordNotLike(String value) {
            addCriterion("FPassword not like", value, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordIn(List<String> values) {
            addCriterion("FPassword in", values, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordNotIn(List<String> values) {
            addCriterion("FPassword not in", values, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordBetween(String value1, String value2) {
            addCriterion("FPassword between", value1, value2, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFpasswordNotBetween(String value1, String value2) {
            addCriterion("FPassword not between", value1, value2, "fpassword");
            return (Criteria) this;
        }

        public Criteria andFstatusIsNull() {
            addCriterion("FStatus is null");
            return (Criteria) this;
        }

        public Criteria andFstatusIsNotNull() {
            addCriterion("FStatus is not null");
            return (Criteria) this;
        }

        public Criteria andFstatusEqualTo(Boolean value) {
            addCriterion("FStatus =", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotEqualTo(Boolean value) {
            addCriterion("FStatus <>", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusGreaterThan(Boolean value) {
            addCriterion("FStatus >", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FStatus >=", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusLessThan(Boolean value) {
            addCriterion("FStatus <", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusLessThanOrEqualTo(Boolean value) {
            addCriterion("FStatus <=", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusIn(List<Boolean> values) {
            addCriterion("FStatus in", values, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotIn(List<Boolean> values) {
            addCriterion("FStatus not in", values, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusBetween(Boolean value1, Boolean value2) {
            addCriterion("FStatus between", value1, value2, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FStatus not between", value1, value2, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFheadurlIsNull() {
            addCriterion("FHeadUrl is null");
            return (Criteria) this;
        }

        public Criteria andFheadurlIsNotNull() {
            addCriterion("FHeadUrl is not null");
            return (Criteria) this;
        }

        public Criteria andFheadurlEqualTo(String value) {
            addCriterion("FHeadUrl =", value, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlNotEqualTo(String value) {
            addCriterion("FHeadUrl <>", value, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlGreaterThan(String value) {
            addCriterion("FHeadUrl >", value, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlGreaterThanOrEqualTo(String value) {
            addCriterion("FHeadUrl >=", value, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlLessThan(String value) {
            addCriterion("FHeadUrl <", value, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlLessThanOrEqualTo(String value) {
            addCriterion("FHeadUrl <=", value, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlLike(String value) {
            addCriterion("FHeadUrl like", value, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlNotLike(String value) {
            addCriterion("FHeadUrl not like", value, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlIn(List<String> values) {
            addCriterion("FHeadUrl in", values, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlNotIn(List<String> values) {
            addCriterion("FHeadUrl not in", values, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlBetween(String value1, String value2) {
            addCriterion("FHeadUrl between", value1, value2, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFheadurlNotBetween(String value1, String value2) {
            addCriterion("FHeadUrl not between", value1, value2, "fheadurl");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeEqualTo(Date value) {
            addCriterion("FCreateTime =", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotEqualTo(Date value) {
            addCriterion("FCreateTime <>", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThan(Date value) {
            addCriterion("FCreateTime >", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FCreateTime >=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThan(Date value) {
            addCriterion("FCreateTime <", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("FCreateTime <=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIn(List<Date> values) {
            addCriterion("FCreateTime in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotIn(List<Date> values) {
            addCriterion("FCreateTime not in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeBetween(Date value1, Date value2) {
            addCriterion("FCreateTime between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("FCreateTime not between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFbalanceIsNull() {
            addCriterion("FBalance is null");
            return (Criteria) this;
        }

        public Criteria andFbalanceIsNotNull() {
            addCriterion("FBalance is not null");
            return (Criteria) this;
        }

        public Criteria andFbalanceEqualTo(Float value) {
            addCriterion("FBalance =", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceNotEqualTo(Float value) {
            addCriterion("FBalance <>", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceGreaterThan(Float value) {
            addCriterion("FBalance >", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceGreaterThanOrEqualTo(Float value) {
            addCriterion("FBalance >=", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceLessThan(Float value) {
            addCriterion("FBalance <", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceLessThanOrEqualTo(Float value) {
            addCriterion("FBalance <=", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceIn(List<Float> values) {
            addCriterion("FBalance in", values, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceNotIn(List<Float> values) {
            addCriterion("FBalance not in", values, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceBetween(Float value1, Float value2) {
            addCriterion("FBalance between", value1, value2, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceNotBetween(Float value1, Float value2) {
            addCriterion("FBalance not between", value1, value2, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFautopayIsNull() {
            addCriterion("FAutoPay is null");
            return (Criteria) this;
        }

        public Criteria andFautopayIsNotNull() {
            addCriterion("FAutoPay is not null");
            return (Criteria) this;
        }

        public Criteria andFautopayEqualTo(Integer value) {
            addCriterion("FAutoPay =", value, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayNotEqualTo(Integer value) {
            addCriterion("FAutoPay <>", value, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayGreaterThan(Integer value) {
            addCriterion("FAutoPay >", value, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayGreaterThanOrEqualTo(Integer value) {
            addCriterion("FAutoPay >=", value, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayLessThan(Integer value) {
            addCriterion("FAutoPay <", value, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayLessThanOrEqualTo(Integer value) {
            addCriterion("FAutoPay <=", value, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayIn(List<Integer> values) {
            addCriterion("FAutoPay in", values, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayNotIn(List<Integer> values) {
            addCriterion("FAutoPay not in", values, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayBetween(Integer value1, Integer value2) {
            addCriterion("FAutoPay between", value1, value2, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFautopayNotBetween(Integer value1, Integer value2) {
            addCriterion("FAutoPay not between", value1, value2, "fautopay");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeIsNull() {
            addCriterion("FCouponCode is null");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeIsNotNull() {
            addCriterion("FCouponCode is not null");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeEqualTo(String value) {
            addCriterion("FCouponCode =", value, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeNotEqualTo(String value) {
            addCriterion("FCouponCode <>", value, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeGreaterThan(String value) {
            addCriterion("FCouponCode >", value, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeGreaterThanOrEqualTo(String value) {
            addCriterion("FCouponCode >=", value, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeLessThan(String value) {
            addCriterion("FCouponCode <", value, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeLessThanOrEqualTo(String value) {
            addCriterion("FCouponCode <=", value, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeLike(String value) {
            addCriterion("FCouponCode like", value, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeNotLike(String value) {
            addCriterion("FCouponCode not like", value, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeIn(List<String> values) {
            addCriterion("FCouponCode in", values, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeNotIn(List<String> values) {
            addCriterion("FCouponCode not in", values, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeBetween(String value1, String value2) {
            addCriterion("FCouponCode between", value1, value2, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodeNotBetween(String value1, String value2) {
            addCriterion("FCouponCode not between", value1, value2, "fcouponcode");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusIsNull() {
            addCriterion("FCouponCodeStatus is null");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusIsNotNull() {
            addCriterion("FCouponCodeStatus is not null");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusEqualTo(Integer value) {
            addCriterion("FCouponCodeStatus =", value, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusNotEqualTo(Integer value) {
            addCriterion("FCouponCodeStatus <>", value, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusGreaterThan(Integer value) {
            addCriterion("FCouponCodeStatus >", value, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("FCouponCodeStatus >=", value, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusLessThan(Integer value) {
            addCriterion("FCouponCodeStatus <", value, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusLessThanOrEqualTo(Integer value) {
            addCriterion("FCouponCodeStatus <=", value, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusIn(List<Integer> values) {
            addCriterion("FCouponCodeStatus in", values, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusNotIn(List<Integer> values) {
            addCriterion("FCouponCodeStatus not in", values, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusBetween(Integer value1, Integer value2) {
            addCriterion("FCouponCodeStatus between", value1, value2, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFcouponcodestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("FCouponCodeStatus not between", value1, value2, "fcouponcodestatus");
            return (Criteria) this;
        }

        public Criteria andFopenidIsNull() {
            addCriterion("FOpenID is null");
            return (Criteria) this;
        }

        public Criteria andFopenidIsNotNull() {
            addCriterion("FOpenID is not null");
            return (Criteria) this;
        }

        public Criteria andFopenidEqualTo(String value) {
            addCriterion("FOpenID =", value, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidNotEqualTo(String value) {
            addCriterion("FOpenID <>", value, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidGreaterThan(String value) {
            addCriterion("FOpenID >", value, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidGreaterThanOrEqualTo(String value) {
            addCriterion("FOpenID >=", value, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidLessThan(String value) {
            addCriterion("FOpenID <", value, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidLessThanOrEqualTo(String value) {
            addCriterion("FOpenID <=", value, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidLike(String value) {
            addCriterion("FOpenID like", value, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidNotLike(String value) {
            addCriterion("FOpenID not like", value, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidIn(List<String> values) {
            addCriterion("FOpenID in", values, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidNotIn(List<String> values) {
            addCriterion("FOpenID not in", values, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidBetween(String value1, String value2) {
            addCriterion("FOpenID between", value1, value2, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFopenidNotBetween(String value1, String value2) {
            addCriterion("FOpenID not between", value1, value2, "fopenid");
            return (Criteria) this;
        }

        public Criteria andFshareamountIsNull() {
            addCriterion("FShareAmount is null");
            return (Criteria) this;
        }

        public Criteria andFshareamountIsNotNull() {
            addCriterion("FShareAmount is not null");
            return (Criteria) this;
        }

        public Criteria andFshareamountEqualTo(Float value) {
            addCriterion("FShareAmount =", value, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountNotEqualTo(Float value) {
            addCriterion("FShareAmount <>", value, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountGreaterThan(Float value) {
            addCriterion("FShareAmount >", value, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountGreaterThanOrEqualTo(Float value) {
            addCriterion("FShareAmount >=", value, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountLessThan(Float value) {
            addCriterion("FShareAmount <", value, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountLessThanOrEqualTo(Float value) {
            addCriterion("FShareAmount <=", value, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountIn(List<Float> values) {
            addCriterion("FShareAmount in", values, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountNotIn(List<Float> values) {
            addCriterion("FShareAmount not in", values, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountBetween(Float value1, Float value2) {
            addCriterion("FShareAmount between", value1, value2, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFshareamountNotBetween(Float value1, Float value2) {
            addCriterion("FShareAmount not between", value1, value2, "fshareamount");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceIsNull() {
            addCriterion("FShareBalance is null");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceIsNotNull() {
            addCriterion("FShareBalance is not null");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceEqualTo(Float value) {
            addCriterion("FShareBalance =", value, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceNotEqualTo(Float value) {
            addCriterion("FShareBalance <>", value, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceGreaterThan(Float value) {
            addCriterion("FShareBalance >", value, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceGreaterThanOrEqualTo(Float value) {
            addCriterion("FShareBalance >=", value, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceLessThan(Float value) {
            addCriterion("FShareBalance <", value, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceLessThanOrEqualTo(Float value) {
            addCriterion("FShareBalance <=", value, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceIn(List<Float> values) {
            addCriterion("FShareBalance in", values, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceNotIn(List<Float> values) {
            addCriterion("FShareBalance not in", values, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceBetween(Float value1, Float value2) {
            addCriterion("FShareBalance between", value1, value2, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFsharebalanceNotBetween(Float value1, Float value2) {
            addCriterion("FShareBalance not between", value1, value2, "fsharebalance");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountIsNull() {
            addCriterion("FOccurredAmount is null");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountIsNotNull() {
            addCriterion("FOccurredAmount is not null");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountEqualTo(Float value) {
            addCriterion("FOccurredAmount =", value, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountNotEqualTo(Float value) {
            addCriterion("FOccurredAmount <>", value, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountGreaterThan(Float value) {
            addCriterion("FOccurredAmount >", value, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountGreaterThanOrEqualTo(Float value) {
            addCriterion("FOccurredAmount >=", value, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountLessThan(Float value) {
            addCriterion("FOccurredAmount <", value, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountLessThanOrEqualTo(Float value) {
            addCriterion("FOccurredAmount <=", value, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountIn(List<Float> values) {
            addCriterion("FOccurredAmount in", values, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountNotIn(List<Float> values) {
            addCriterion("FOccurredAmount not in", values, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountBetween(Float value1, Float value2) {
            addCriterion("FOccurredAmount between", value1, value2, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFoccurredamountNotBetween(Float value1, Float value2) {
            addCriterion("FOccurredAmount not between", value1, value2, "foccurredamount");
            return (Criteria) this;
        }

        public Criteria andFcardnumIsNull() {
            addCriterion("FCardNum is null");
            return (Criteria) this;
        }

        public Criteria andFcardnumIsNotNull() {
            addCriterion("FCardNum is not null");
            return (Criteria) this;
        }

        public Criteria andFcardnumEqualTo(String value) {
            addCriterion("FCardNum =", value, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumNotEqualTo(String value) {
            addCriterion("FCardNum <>", value, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumGreaterThan(String value) {
            addCriterion("FCardNum >", value, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumGreaterThanOrEqualTo(String value) {
            addCriterion("FCardNum >=", value, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumLessThan(String value) {
            addCriterion("FCardNum <", value, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumLessThanOrEqualTo(String value) {
            addCriterion("FCardNum <=", value, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumLike(String value) {
            addCriterion("FCardNum like", value, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumNotLike(String value) {
            addCriterion("FCardNum not like", value, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumIn(List<String> values) {
            addCriterion("FCardNum in", values, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumNotIn(List<String> values) {
            addCriterion("FCardNum not in", values, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumBetween(String value1, String value2) {
            addCriterion("FCardNum between", value1, value2, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFcardnumNotBetween(String value1, String value2) {
            addCriterion("FCardNum not between", value1, value2, "fcardnum");
            return (Criteria) this;
        }

        public Criteria andFsceneIsNull() {
            addCriterion("FScene is null");
            return (Criteria) this;
        }

        public Criteria andFsceneIsNotNull() {
            addCriterion("FScene is not null");
            return (Criteria) this;
        }

        public Criteria andFsceneEqualTo(String value) {
            addCriterion("FScene =", value, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneNotEqualTo(String value) {
            addCriterion("FScene <>", value, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneGreaterThan(String value) {
            addCriterion("FScene >", value, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneGreaterThanOrEqualTo(String value) {
            addCriterion("FScene >=", value, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneLessThan(String value) {
            addCriterion("FScene <", value, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneLessThanOrEqualTo(String value) {
            addCriterion("FScene <=", value, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneLike(String value) {
            addCriterion("FScene like", value, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneNotLike(String value) {
            addCriterion("FScene not like", value, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneIn(List<String> values) {
            addCriterion("FScene in", values, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneNotIn(List<String> values) {
            addCriterion("FScene not in", values, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneBetween(String value1, String value2) {
            addCriterion("FScene between", value1, value2, "fscene");
            return (Criteria) this;
        }

        public Criteria andFsceneNotBetween(String value1, String value2) {
            addCriterion("FScene not between", value1, value2, "fscene");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_AppUser
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 11 12:42:32 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}