package com.yadda.integrate.model;

public class SecurityResources extends RootModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.ID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.CATEGORY
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.VERSION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.DESCRIPTION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.NAME
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.LEVEL
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.MENU_ICON
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String menuIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.POSITION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.URL
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KS_SECURITYRESOURCES.IDENTIFIER
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    private String identifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.ID
     *
     * @return the value of KS_SECURITYRESOURCES.ID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.ID
     *
     * @param id the value for KS_SECURITYRESOURCES.ID
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.CATEGORY
     *
     * @return the value of KS_SECURITYRESOURCES.CATEGORY
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.CATEGORY
     *
     * @param category the value for KS_SECURITYRESOURCES.CATEGORY
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.VERSION
     *
     * @return the value of KS_SECURITYRESOURCES.VERSION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.VERSION
     *
     * @param version the value for KS_SECURITYRESOURCES.VERSION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.DESCRIPTION
     *
     * @return the value of KS_SECURITYRESOURCES.DESCRIPTION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.DESCRIPTION
     *
     * @param description the value for KS_SECURITYRESOURCES.DESCRIPTION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.NAME
     *
     * @return the value of KS_SECURITYRESOURCES.NAME
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.NAME
     *
     * @param name the value for KS_SECURITYRESOURCES.NAME
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.LEVEL
     *
     * @return the value of KS_SECURITYRESOURCES.LEVEL
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.LEVEL
     *
     * @param level the value for KS_SECURITYRESOURCES.LEVEL
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.MENU_ICON
     *
     * @return the value of KS_SECURITYRESOURCES.MENU_ICON
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.MENU_ICON
     *
     * @param menuIcon the value for KS_SECURITYRESOURCES.MENU_ICON
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon == null ? null : menuIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.POSITION
     *
     * @return the value of KS_SECURITYRESOURCES.POSITION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.POSITION
     *
     * @param position the value for KS_SECURITYRESOURCES.POSITION
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.URL
     *
     * @return the value of KS_SECURITYRESOURCES.URL
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.URL
     *
     * @param url the value for KS_SECURITYRESOURCES.URL
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KS_SECURITYRESOURCES.IDENTIFIER
     *
     * @return the value of KS_SECURITYRESOURCES.IDENTIFIER
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KS_SECURITYRESOURCES.IDENTIFIER
     *
     * @param identifier the value for KS_SECURITYRESOURCES.IDENTIFIER
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }
}